### ISSUE TITLE
ScalaPB is unable to convert timestamp column to protobuf timestamp

### ISSUE THREAD

**Issue by Veske** [scalapb/sparksql-scalapb#111]
Doing so will result in
```
Can't extract value from timestamp#6: need struct type but got timestamp;
org.apache.spark.sql.AnalysisException: Can't extract value from timestamp#6: need struct type but got timestamp;
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:73)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$resolveExpression$1.applyOrElse(Analyzer.scala:1154)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$resolveExpression$1.applyOrElse(Analyzer.scala:1145)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$4(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
```

I created a test repo here: https://github.com/Veske/protobuf-timestamp    
Run the ConvertTimestamp test and verify that it succeeds (`AnalysisException` is thrown)

**Comment by thesamet** [comment]
Protobuf timestamp has nanosecond resolution, and Spark's timestamp has microsecond precision, so a conversion by default would introduce information loss. We could make it an option (like we do with `ProtoSQL.withPrimitiveWrappers`), but that requires some digging into the code, and perhaps it's better to do this following the Spark 3.0.0 support.

However, for the time being, it is recommended to write a custom `ProtoSQL.udf` to convert between sql.Timestamp and protobuf Timestamp and use that when this conversion is needed.

**Comment by Veske** [comment]
Thanks! A `udf` will be the way to go for me for now then. I guess you can feel free to close it in that case.
