### ISSUE TITLE
Support missing repeated fields in json input

### ISSUE THREAD

**Issue by AlexisBRENON** [scalapb/sparksql-scalapb#211]
When loading data from json input, it can happen that an empty repeated field is missing from the input.
In this case, deserialization fails with a `NullPointerException`.

For example, given the following protobuf message and the Spark reading sample:
```protobuf
syntax = "proto3";

package mypackage;

message MyRepeated {
  repeated string ListField = 1;
}
```

```scala
import scalapb.spark.Implicits._
val dataPath = "/home/alexis/tmp/proto_spark/src/main/resources/repeated"
println(spark.read
  .schema(spark.emptyDataset[MyRepeated].schema)
  .json(dataPath)
  .as[MyRepeated]
  .collect()
  .mkString("\n")
)
```

It is possible to read the following file:
```json
{"ListField": ["foo", "bar"]}
{"ListField": []}
```

But this one throws the following error:
```json
{"ListField": ["foo", "bar"]}
{"ListField": []}
{}
```

```
Exception in thread "main" java.lang.NullPointerException
    at mypackage.repeated.MyRepeated$.$anonfun$messageReads$4(MyRepeated.scala:84)
    at scala.Option.map(Option.scala:230)
    at mypackage.repeated.MyRepeated$.$anonfun$messageReads$1(MyRepeated.scala:84)
```
```
    80    implicit def messageReads: _root_.scalapb.descriptors.Reads[com.adyoulike.data.proto.repeated.MyRepeated] = _root_.scalapb.descriptors.Reads{
    81      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
    82        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
    83        com.adyoulike.data.proto.repeated.MyRepeated(
>   84          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty)
    85        )
    86      case _ => throw new RuntimeException("Expected PMessage")
    87    }
```

This is because ([gitter thread](https://gitter.im/ScalaPB/community?at=616117422197144e8455948b))
> when columns are missing in the json input, spark puts in nulls for the missing value. ScalaPB expects empty arrays and not nulls when parsing a dataframe

Current workaround is to put empty array instead of null value before any use of the Encoder:
```scala
spark.read
  .schema(spark.emptyDataset[MyRepeated].schema)
  .json(dataPath)
  .withColumn("listField", F.coalesce(F.col("listField"), F.array())) // Convert null values to empty arrays
  .as[MyRepeated]
  .collect()
```

**Comment by AlexisBRENON** [comment]
This is fixed by #220 and #217
