### ISSUE TITLE
sparksql-scalapb  java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.objects.Invoke. 

### ISSUE THREAD

**Issue by sujitbiswas** [scalapb/sparksql-scalapb#260]
using

maven project with dependency 

```
<dependency>
			<groupId>com.thesamet.scalapb</groupId>
			<artifactId>sparksql32-scalapb0_11_2.12</artifactId>
			<version>1.0.0-M1</version>
</dependency>
```

scala code looks as below

```
test(testName = "spark-scala-pb") {

    import org.apache.spark.sql.{ DataFrame, Dataset, functions => F }

    import scalapb.spark.ProtoSQL
    import spark.implicits.StringToColumn

    

    import scalapb.spark.Implicits._

    val inputData = Seq(nvFrame, nvFrame).map(_.toByteArray)

    val ds = spark.createDataset(inputData)

    val r = ds.map { f =>
      val x = Frame.parseFrom(f)
      x
    }

    r.count();

  }
```

Run starting. Expected test count is: 1
FrameTest3:
22/03/17 20:30:53 WARN util.Utils: Your hostname, SUJITB-MLT-2.local resolves to a loopback address: 127.0.0.1; using 10.0.0.52 instead (on interface en0)
22/03/17 20:30:53 WARN util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
22/03/17 20:30:53 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
*** RUN ABORTED ***
  java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.objects.Invoke.<init>(Lorg/apache/spark/sql/catalyst/expressions/Expression;Ljava/lang/String;Lorg/apache/spark/sql/types/DataType;Lscala/collection/Seq;Lscala/collection/Seq;ZZ)V
  at scalapb.spark.ToCatalystHelpers.getField$1(ToCatalystHelpers.scala:64)
  at scalapb.spark.ToCatalystHelpers.$anonfun$fieldGetterAndTransformer$1(ToCatalystHelpers.scala:91)
  at scalapb.spark.ToCatalystHelpers.fieldToCatalyst(ToCatalystHelpers.scala:164)
  at scalapb.spark.ToCatalystHelpers.fieldToCatalyst$(ToCatalystHelpers.scala:102)
  at scalapb.spark.Implicits$$anon$1.fieldToCatalyst(TypedEncoders.scala:127)
  at scalapb.spark.ToCatalystHelpers.$anonfun$messageToCatalyst$2(ToCatalystHelpers.scala:36)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  ...

can you please help? how to resolve

note the code works fine outside of spark 

`val x = Frame.parseFrom(f)`

**Comment by sujitbiswas** [comment]
the issue is with

<spark.version>3.2.1</spark.version>

it works with

<spark.version>3.2.0</spark.version>
